[package]
name = "dashboard_rust"
version = "0.1.0"
edition = "2021"

[dependencies]
serialport = "4.2.2"
eframe = "0.27"
egui = "0.27"
egui_plot = "0.27"
chrono = "0.4"
egui_extras = { version = "*", features = ["all_loaders"] }
image = { version = "0.24.6", features = ["jpeg", "png"] }